"""OpenAI code_interpreter tool support: build the tool config, and mirror any
generated output files to our own GCP storage before the response reaches the
user.

Container files (code_interpreter outputs) are NOT Files-API files — they live
in an ephemeral container that expires ~20 min after last use. We must
download them immediately and store our own copy; handing the user a
container file reference would break as soon as the container is gone.

Confirmed against OpenAI's official docs + community reports (2026-07):
  - `container_file_citation` annotations are the *intended* mechanism
    ("Files and images generated by the model are returned as annotations on
    the assistant's message... it cites these files in the annotations of its
    next message" — OpenAI Code Interpreter guide) but are NOT guaranteed for
    every generated file.
  - OpenAI staff acknowledged on the developer forum this is a known,
    unresolved gap: "the documentation describes the expected behavior, but
    the actual implementation can be inconsistent, particularly for
    non-primary or subsequent files." Their own mitigation is: "increased
    annotation odds and ensured files upload to the /v1/containers endpoint
    as a fallback, but the core limitation remains."
  - Their (and the community's) recommended workaround is exactly what this
    module does: poll `GET /v1/containers/{id}/files` as the reliable
    fallback when a citation is missing — this lists files regardless of
    annotation status. It is still not instantaneous (see _list_container_files).
  - Container file `source` field values are officially documented as "user"
    and "assistant" (OpenAI Containers API reference) — our exclusion check
    matches the documented schema, not a guess.
"""

import asyncio
import mimetypes
import os

from globals import logger
from src.configs.constant import service_name
from src.configs.service_registry import code_interpreter_tool_config
from src.services.utils.apiservice import fetch
from src.services.utils.gcp_upload_service import uploadDoc

_CONTAINERS_BASE_URL = "https://api.openai.com/v1/containers"
_DEBUG_TEXT_LIMIT = 2000
_LIST_RETRY_ATTEMPTS = 5
_LIST_RETRY_DELAYS_SECONDS = [1, 2, 3, 4]


def _log_code_interpreter_debug(modelResponse: dict):
    """Log what the model actually did with code_interpreter this turn.

    Diagnoses the "tool ran but returned the file unchanged" symptom: logs the
    executed code, its status, and any logs/error outputs for every
    code_interpreter_call item, so it's visible whether the model errored out
    (e.g. missing library, no AcroForm fields) and silently gave up, or never
    invoked the tool at all.
    """
    calls = [
        item
        for item in (modelResponse.get("output", []) or [])
        if isinstance(item, dict) and item.get("type") == "code_interpreter_call"
    ]
    if not calls:
        return

    for call in calls:
        code = (call.get("code") or "")[:_DEBUG_TEXT_LIMIT]
        outputs = call.get("outputs") or []
        rendered_outputs = []
        for out in outputs:
            if isinstance(out, dict) and out.get("type") == "logs":
                rendered_outputs.append({"type": "logs", "logs": (out.get("logs") or "")[:_DEBUG_TEXT_LIMIT]})
            elif isinstance(out, dict):
                rendered_outputs.append({"type": out.get("type"), "keys": list(out.keys())})
        logger.info(
            "code_interpreter debug: id=%s status=%s container_id=%s code=%r outputs=%s"
            % (call.get("id"), call.get("status"), call.get("container_id"), code, rendered_outputs)
        )


def _headers(apikey: str) -> dict:
    return {"Authorization": f"Bearer {apikey}"}


def build_code_interpreter_tool(input_file_ids: list[str] | None = None) -> dict:
    """Native code_interpreter tool shape, DB/fallback-driven via service_registry
    (same pattern as web_search_tool_config / image_generation_tool_config).
    The `container` (dynamic per request) is merged in here."""
    tool = dict(code_interpreter_tool_config(service_name["openai"]) or {"type": "code_interpreter"})
    container = {"type": "auto"}
    if input_file_ids:
        container["file_ids"] = input_file_ids
    tool["container"] = container
    return tool


def _extract_citations_and_container(modelResponse: dict) -> tuple[str | None, list[dict]]:
    """Pull container_file_citation annotations (read-only) from the message,
    plus the container_id (from a citation or the code_interpreter_call item).

    These are only used as a source of file_id/filename — the citation dicts
    themselves are left untouched; results are reported via
    modelResponse["generated_files"], not by mutating annotations."""
    citations = []
    container_id = None
    for item in modelResponse.get("output", []) or []:
        if not isinstance(item, dict):
            continue
        if item.get("type") == "code_interpreter_call":
            container_id = item.get("container_id") or container_id
        elif item.get("type") == "message":
            for content in item.get("content", []) or []:
                for ann in content.get("annotations", []) or []:
                    if isinstance(ann, dict) and ann.get("type") == "container_file_citation":
                        citations.append(dict(ann))
                        container_id = container_id or ann.get("container_id")
    return container_id, citations


def _is_mounted_input_file(cf: dict, exclude_file_ids: set[str]) -> bool:
    if cf.get("source") == "user":
        return True
    path = cf.get("path") or ""
    return any(exclude_id and exclude_id in path for exclude_id in exclude_file_ids)


async def _list_container_files_once(container_id: str, apikey: str, exclude_file_ids: set[str]) -> list[dict]:
    try:
        data, _ = await fetch(url=f"{_CONTAINERS_BASE_URL}/{container_id}/files", headers=_headers(apikey))
    except Exception as e:
        logger.error(f"code_interpreter: failed to list container {container_id} files: {e}")
        return []

    raw_files = data.get("data", []) or []
    logger.info(
        "code_interpreter debug: container %s files.list full_response=%r exclude_file_ids=%r"
        % (container_id, data, exclude_file_ids)
    )

    entries = []
    for cf in raw_files:
        file_id = cf.get("id")
        if not file_id or _is_mounted_input_file(cf, exclude_file_ids):
            continue
        path = cf.get("path") or ""
        filename = os.path.basename(path) or file_id
        entries.append({"container_id": container_id, "file_id": file_id, "filename": filename})
    return entries


async def _list_container_files(container_id: str, apikey: str, exclude_file_ids: set[str]) -> list[dict]:
    """Fallback when no annotations are present: list all container files,
    skipping the ones we mounted ourselves as input.

    Retries with backoff (up to ~10s total) — a file the code just wrote isn't
    always visible on the very next files.list() call. This is an OpenAI
    platform gap, not something we can fix outright: their own staff describe
    it as a known, unresolved limitation (see module docstring). Non-input
    files not found immediately may simply not have landed yet.
    """
    for attempt in range(_LIST_RETRY_ATTEMPTS):
        entries = await _list_container_files_once(container_id, apikey,[])
        if entries:
            return entries
        if attempt < _LIST_RETRY_ATTEMPTS - 1:
            await asyncio.sleep(_LIST_RETRY_DELAYS_SECONDS[attempt])
    return []


async def _download_container_file(container_id: str, file_id: str, apikey: str) -> bytes | None:
    try:
        content, _ = await fetch(
            url=f"{_CONTAINERS_BASE_URL}/{container_id}/files/{file_id}/content",
            headers=_headers(apikey),
            image=True,  # fetch() returns raw bytes (BytesIO) instead of parsing JSON
        )
        return content.read()
    except Exception as e:
        logger.error(f"code_interpreter: failed to download container file {file_id}: {e}")
        return None


async def process_code_interpreter_outputs(modelResponse: dict, apikey: str, input_file_ids: list[str] | None = None):
    """Mirror any code_interpreter-generated files to our GCP bucket.

    Reports results via modelResponse["generated_files"] — a plain list of
    {"file_id", "filename", "gcp_url"} — rather than mutating annotations.
    Formatters/history surface these through "llm_urls" (type="file"), the
    same field already used for image_generation_call outputs, instead of
    piggybacking on provider citation objects.
    """
    _log_code_interpreter_debug(modelResponse)

    container_id, citations = _extract_citations_and_container(modelResponse)
    if not container_id:
        return

    exclude_file_ids = set(input_file_ids or [])
    raw_entries = citations or await _list_container_files(container_id, apikey, exclude_file_ids)
    entries = [entry for entry in raw_entries if entry.get("file_id") not in exclude_file_ids]
    if not entries:
        return

    generated_files = []
    for entry in entries:
        entry_container_id = entry.get("container_id") or container_id
        file_id = entry.get("file_id")
        if not file_id:
            continue
        data = await _download_container_file(entry_container_id, file_id, apikey)
        if data is None:
            continue
        filename = entry.get("filename") or file_id
        content_type, _ = mimetypes.guess_type(filename)
        gcp_url = await uploadDoc(
            file=data,
            folder="code-interpreter-outputs",
            real_time=True,
            content_type=content_type or "application/octet-stream",
            original_filename=filename,
        )
        generated_files.append({"file_id": file_id, "filename": filename, "gcp_url": gcp_url})

    if generated_files:
        modelResponse.setdefault("generated_files", []).extend(generated_files)
